_target_: dataset.geom_data.GEOM_data
name: "geom_drug"
args:
  data_name: GEOM_drug
  node_coarse_type: prop
  #feature_size: 8
  #feature_size: 4
  vocab_path: dataset/vocab.txt
  vocab_fp_path_elem: dataset/atom_embed.csv
  vocab_fp_path_prop: dataset/vocab_blur_fps_updated.csv
  data_dir: data/GEOM_drugs_trees_blur_correct_adj

  dataloader_config:
    batch_size: 16
    num_workers: 16
    pin_memory: True
