vocab_path: dataset/vocab.txt
vocab_fp_path: dataset/vocab_blur_fps_updated.csv

dataloader:
  batch_size: 128
  num_workers: 20
  shuffle: True
  pin_memory: True

dataset:
  data_dir: data/crossdock_data/trees
  split: data/crossdock_data/denoise_split.pkl
  int_feature_size: 5
  num_continutes_feature: 3
  context_nf: 0
  vocab_size: 781
  search_mode: dfs_bidirection
  search_priority: False
  full_softmax: True
  #array_dict: dataset/atom_embed_dict.pkl