vocab_path: dataset/vocab.txt
node_coarse_type: prop

vocab_fp_path_prop: dataset/vocab_blur_fps_updated.csv
vocab_fp_path_elem: dataset/atom_embed.csv

dataloader:
  batch_size: 2
  num_workers: 2
  shuffle: True
  pin_memory: True

dataset:
  node_coarse_type: prop
  data_dir: data/GEOM_drugs_trees_blur_correct_adj
  split: data/geom_denoise_split.pkl
  feature_size: 0
  context_nf: 0
  vocab_size: 781
  search_mode: dfs_bidirection
  full_softmax: True
  array_dict: dataset/atom_embed_dict.pkl