vocab_path: dataset/vocab.txt
vocab_fp_path: dataset/atom_embed.csv
int_feature_size: 5
num_continutes_feature: 3

dataset:
  data_dir: data/crossdock_data/trees


dataloader:
  batch_size: 128
  num_workers: 32
  pin_memory: True

