vocab_path: dataset/vocab.txt
node_coarse_type: prop

vocab_fp_path_prop: dataset/vocab_blur_fps_updated.csv
vocab_fp_path_elem: dataset/atom_embed.csv
int_feature_size: 5
num_continutes_feature: 3

dataset:
  node_coarse_type: prop
  data_dir: data/GEOM_drugs_trees_blur_correct_adj


dataloader:
  batch_size: 4
  num_workers: 4
  pin_memory: True

