wandb:
  _target_: pytorch_lightning.loggers.WandbLogger
  save_dir: .
  name: ${model._target_}_${now:%Y-%m-%d_%H-%M-%S}
  version: ${model._target_}_${now:%Y-%m-%d_%H-%M-%S}
  project: "geom_blur"
  tags: []
  notes: ""