accelerator: gpu
devices: [0, 1, 2]
strategy: ddp
weights_summary: top
max_epochs: 200
gradient_clip_val: 1
gradient_clip_algorithm: norm
log_every_n_steps: 10
track_grad_norm: 2
num_sanity_val_steps: 0
default_root_dir: pl_log/refine