accelerator: cuda
strategy: "ddp"
gpus: [1,2,3,4,5]
amp_backend: apex
amp_level: O2
profiler: simple
#deterministic: true
max_epochs: 80 #this will influences the scheduler
gradient_clip_val: 2
gradient_clip_algorithm: norm
log_every_n_steps: 1
track_grad_norm: 2
num_sanity_val_steps: 2
default_root_dir: ./
accumulate_grad_batches: 1
#fast_dev_run: True